[package]
name = "heimdall"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"
description = "Heimdall is an advanced Ethereum smart contract toolkit for forensic and heuristic analysis."
keywords = ["ethereum", "web3", "decompiler", "evm", "crypto"]


[dependencies]
heimdall-common = { path = "./../common" }
heimdall-config = { path = "./../config" }
clap = { version = "3.1.18", features = ["derive"] }
clap-verbosity-flag = "1.0.0"

[[bin]]
name = "heimdall"
path = "src/heimdall.rs"