[package]
name = "heimdall-common"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"
description = "Commonly used resources for heimdall modules."
keywords = ["ethereum", "web3", "decompiler", "evm", "crypto"]

[dependencies]
lazy_static = "1.4.0"
regex = "1.1.5"
clap = { version = "3.1.18", features = ["derive"] }
clap-verbosity-flag = "1.0.0"
ethers = { git = "https://github.com/gakonst/ethers-rs" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"