name: Publish

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Publish Binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Binaries
      working-directory: ./heimdall
      run:  cargo build --release
    - name: Upload Binaries
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./heimdall/target/release/heimdall
        asset_name: heimdall
        tag: ${{ github.ref }}
        overwrite: true